import type { Metadata } from "next";
import "./globals.css";
import { AnalysisProvider } from "../lib/context/AnalysisContext";
import Navbar from "../components/Navbar";
import { geistSans, geistMono } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AnalysisProvider><Navbar />
          <main>
            {children}
          </main></AnalysisProvider>
      </body>
    </html>
  );
}
